mqtt:
  internalBroker:
    enabled: true
    hostname: 127.0.0.1
    useSSL: false
  externalBroker:
    enabled: true
    hostname: rv-dev.eastasia.cloudapp.azure.com
    useSSL: false
  webPubSub:
    enabled: false
    connectionString: Endpoint=https://rv-arcs.webpubsub.azure.com;AccessKey=3ThHfey9ewz4Pt227EcTXIbjs6y7bbT+0RJ5gq3fO6U=;Version=1.0;
    hub: ${system.tenantId}
ros:
  rosNode:
    tilt:
      enabled: true
      angle: '10'
    sickPlcIo:
      enabled: false
    followRobotPairing:
      enabled: true
    charging:
      enabled: true
    map:
      path: /home/europa/maps/%s/
    baseIo:
      enabled: true
      version: STM32
    led:
      version: 3
    fan:
      enabled: false
    cabinet:
      enabled: true
system-sensor:
  autoStartup:
    enabled: true
    interval: 60000
system:
  robotType: DELIVERY
  robotSubtype: CABINET_DELIVERY
  robotId: RV-ROBOT-102
  heartbeat:
    enabled: true
    interval: 60000
  fms:
    enabled: true
    baseUrl: https://rv-arcs-fms.azurewebsites.net/api
schmidt:
  enabled: true
rosbridge:
  fzi:
    enabled: true
    hostname: localhost
    port: 9091
  cotek:
    enabled: true
    hostname: ${rosbridge.fzi.hostname}
